version: "3.8"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin       # default username
      - GF_SECURITY_ADMIN_PASSWORD=admin   # default password
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
