version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.10
    ports:
      - "3101:3100" # Loki API
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    user: "${UID}:${UID}"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000" # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/var/lib/grafana
    user: "${UID}:${UID}"
    depends_on:
      - loki

volumes:
  grafana-data:
  loki-data:
