name: Notify Discord on GitHub Events

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - closed
      - reopened
  issues:
    types:
      - opened
      - closed
      - reopened
  issue_comment:
    types:
      - created
  fork:
  create:
  delete:
  release:
    types:
      - published
  workflow_dispatch:  # Allows manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          EVENT_NAME: ${{ github.event_name }}
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          MESSAGE=$(cat <<EOF
          🔔 **GitHub Event Triggered!**
          📢 **Event:** $EVENT_NAME
          👤 **Triggered by:** $ACTOR
          📂 **Repository:** $REPO
          🔗 [View Workflow Run](https://github.com/$REPO/actions/runs/$RUN_ID)
          EOF
          )

          ESCAPED_MESSAGE=$(echo "$MESSAGE" | jq -Rs .)

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\": \"GitHub Actions\", \"content\": $ESCAPED_MESSAGE}" \
               "$DISCORD_WEBHOOK"